Main
simt11/Calculator pull request #1
Opened 2022-11-29 14:32 UTC by simt11

Внесены значительные изменения как в стиль кода, так и в функционал.

2022-11-30 07:50 UTC, fantasianna requested changes
оставила несколько комментов

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            if (bMathR().last() == '=') {
все что внутри setOnClickListener тоже хорошо вынести в отдельный метод, чтобы облегчить читаемость текущего метода

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                for (i in 0..bMathR().length - 1) {
такой фор не камильфо использовать, особенно учитывая, что тебе не нужен индекс
предлагаю заменить на обычный фор
for (element in array)

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun bMathR(): String = binding.mathOperation.text.toString()
все функции лучше сделать приватными методами класса. Глобальные функции создают кашу в коде, мы стараем инкапсулировать по максимуму. Либо, если ты хочешь, чтобы эти функции были доступны многим твоим классам, то лучше сделать класс Utils, который будет хранить такие служебные методы, которые нужны всем в приложении

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun bResuW(str: String) {
все эти 4 метода надо переименовать, что они делают невозможно понять не заглянув в тело метода

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
>  fun addStr(str: String) {
отличный метод! красивый! понятный!

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    if (bMathR().equals("0") || bMathR().last() == '=') {
тут тоже when бы смотрелся лучше, на твое усмотрение

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            if (bMathR().last() == '=') {
bMathR().last() == '=' много таких выражений, где ты у разных строк делаешь проверку на равенство с каким-то символом. Подумай о том, чтобы сделать extension function для строки, которая будет принимать любой символ и возвращать тру, если этот символ есть в конце. Это поможет еще больше улучшить читаемость и переиспользуемость кода. Читаемость для нас очень важна, потому что мы пишем код для людей, а не для машин (как бы парадоксально это ни звучало)

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    } else if (bMathR().last() == '0' && simEqual(bMathR()[bMathR().length - 2])) {
условие внутри этого ифа слишком сложное, эти внутренности надо либо вынести в переменную, либо в функцию

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        btnBack()
я пока не знаю, что делает этот метод, но у меня возникают сильные ассоциации с андроидной кнопкой back и я из-за этого ломаюсь. Лучше не допускать таких пересечений по названиям со значимыми частями андроида

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    if (c == "-" && bMathR() == "0") {
тут стоподуово надо when, ты один раз его попробуешь и вообще забудешь как ифом пользоваться)))

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    if (str.any { it == '.' }) {
очень очень очень сложно, везде в таких случаях больших ветвлений нам нужен when

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    if (bMathR().length > 1) bMathW(bMathR().substring(0, bMathR().length - 1)) else bMathW("0")
разбей пожалуйста весь этот иф тут и везде на несколько строк
if () {
   // body
} else {
// body
}

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun simEqual(sim: Char): Boolean = sim == '/' || sim == '*' || sim == '-' || sim == '+'
кажется эти арифметические символы могут хорошо лечь в enum и тогда необходимость в таких сравнениях отпадет, будет проверка символа на наличие его в енаме

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    var arrElement = str.split("-", "+").filter { it.isNotEmpty() }.toTypedArray()
если тебе не принципиален Array, то лучше использовать List
1) List вообще структура по умолчанию для представления коллекций
2) это поможет избежать дополнительных конвертаций toTypedArray

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun giveMeNumMinusPlus(str: String): Array<String> {
это очень мило, что ты вежливо просишь метод что-то для тебя сделать, но лучше называть его более декларативно (он все стерпит), например, getFilteredList(), ну или что он тебе отдает

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun giveMeNumParenthesis(str: String): Array<String> {
в этих трех методах - дублирование кода, который отличается только символами внутри сплита. Нужно либо схлопнуть все три метода в один, и передавать символы параметрами метода, либо сделать еще один метод, который будет принимать параметры, а в этих трех методах его заиспользовать с передачей нужных символов

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun giveMeSimMinusPlus(str: String): CharArray {
тут тоже два одинаковых метода, нужно избавиться от дублирования

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun MathEqually(numberOne: String, numberTwo: String, sign: Char): String {
1) названия методов всегда начинаются с маленькой буквы
2) названия методов всегда начинаются с глагола

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        value = MathEqually(value, arrNumber[i], arrSimvol[i - 1])
опечатка, тут должен быть не Simvol, а Simbol
в коде все слова переводим на английский

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    val arrSimvol = giveMeSimMinusPlus(str)
не понятно что за два массива arrNumber и arrSimvol, лучше их переназвать, чтобы было понятно, какой их скрытый смысл. Если алгоритм такой сложный, что правильными названиями тут не отделаешься, тогда лучше добавить перед названием метода коммент с описанием алгоритма

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        for (i in 1..arrSimvol.size) {
такая вложенность тоже вызывает трудности при чтении, лучше внутренности фора вынести в отдельный метод, который будет возвращать значение для value

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    when (sign) {
when ❤️❤️❤️❤️❤️

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        else -> return ("Ну хз")
если тут в else происходит что-то невозможное, то можно выкинуть эксепшн, чтобы все разбомбить

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        // TODO: Добавить удаение при долгом нажатие на кнопку Back
удаение

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
>  fun simMath(c: String) {
название параметра функции должно отражать его назначение

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
>  fun simMath(c: String) {
как и название самой функции :)

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun simEqual(sim: Char): Boolean = sim == '/' || sim == '*' || sim == '-' || sim == '+'
там же в енаме можно выставить приоритет арифметических операций и как-то заиспользовать его дальше, когда ты парсишь выражение

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    if (str[0] == '-') arrElement[0] = "-" + arrElement[0]
лучше у строк и коллекций использовать обращение не по индексу, а метод типа .first()

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun giveMeSimMulSub(str: String): CharArray {
не понятно почему некоторые методы возвращают Array<String>, а другие CharArray
может можно привести все к одному типу?

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    return arrElement
если метод возвращает массив, то название переменной должно отражать это, а то получается что arrElement это типа один элемент по названию, а на самом деле это массив стрингов

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        return str.drop(1).filter { it == '/' || it == '*' }.toCharArray()
удостоверься в документации, что drop не вызывает копирования строки, а то это может стать серьезным ударом по производительности, если представить, что какой-то бухгалтер начнет годовой отчет делать на твоем калькуляторе и забьет ооооооооочень длинную строку

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    } else if (simEqual(bMathR().reversed()[i])) {
внутри фора нужно быть очень внимательным, что ты не вызываешь каких-то тяжеловестных операций (типа bMathR().reversed()) все что не зависит от индекса нужно вынести наружу фора и присохранить в переменную

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    } else if (simEqual(bMathR().reversed()[i])) {
проверь на этот принцип все остальные циклы, пожалуйста

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +fun bMathR(): String = binding.mathOperation.text.toString()
много где используется конвертация toString(), может имеет смысл не переходить на стринг каждый раз, а оперировать тем типом, который возвращается в text? что там, CharSequence?

2022-11-30 07:50 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    } else if (bMathR().last() == '0' && simEqual(bMathR()[bMathR().length - 2])) {
bMathR()[bMathR().length - 2] тут приложение упадет, если каким-то чудом сюда придет массив из bMathR() меньше двух символов. Если тебе сильно нужен именно такой подход, то лучше добавить проверку на длину массива

2022-11-30 07:52 UTC, fantasianna commented
после того, как main смерджится в мастер, хорошо бы сделать от мастера ветку development и от нее уже делать следующую фиче ветку

2022-11-30 08:09 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    bMathW(whySoManyZeros(bMathR()))
Типа viewMathRead ?

2022-11-30 08:10 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    bMathW(whySoManyZeros(bMathR()))
Это была шутка. ;) изменю)

2022-11-30 08:12 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    if (bMathR().equals("0") || bMathR().last() == '=') {
Почему when?

2022-11-30 09:18 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    bMathW(whySoManyZeros(bMathR()))
а что он делает русскими словами?

2022-11-30 09:33 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    bMathW(whySoManyZeros(bMathR()))
Записывает данные в поле Текс на экране, переданную строку.
Фактически - это сокращение от binding.mathOperation.text

2022-12-01 02:19 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                    bMathW(whySoManyZeros(bMathR()))
тогда можно что-то вроде setMathOperationText()
есть популярные префиксы для названий методов по их деятельности:
get.. - берет что-то откуда-то, как у тебя. Так же применимо к запросам в БД или на сервер
set.. - устанавливает новое значение в переменную или куда-то, например, у тебя установка нового значения в текстовое поле
is.. - для методов с типом возвращаемого значения bool. Для проверок любых условий. Например, isEmpty, isFinished
has.. - для методов с типом возвращаемого значения bool, но те которые проверяют наличие чего-то в чем-то, напр, hasManyZeros(), hasLastSymbol(String source, char symbol) 
generate.., create.. - что-то создается внутри, например конструируется сложный объект, или происходят сложные вычисления с результатом
clear.. - очистить что-то, чаще всего занулить
load.. - загрузить данные, подходит для запросов к серверу (аналог get)
reset.. - сбросить значение к изначальному (билзко к clear, но тут изначальное значение может быть не null)
route.. - перейти куда-то, напимер на следуюший экран или назад по стеку экранов, напр. routeBack(), routeDeeplink, routeDetailScreen

2022-12-05 13:20 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        for (i in 1..arrSimvol.size) {
Не получилось вынести, перестает работать на проверках 2+2*2 и 2*2+2

2022-12-05 14:19 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                for (i in 0..bMathR().length - 1) {
не получилось вынести. Падает приложение

2022-12-06 14:03 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        return str.drop(1).filter { it == '/' || it == '*' }.toCharArray()
Немного заморочился с этим вопросом. И честно говоря не до конца понимаю итог. 
drop ведь все равно возвращает часть строки, можно ли это считать за копирование?
если углубляться то drop выполняется через take(), который в свою очередь выполняется через substring(), которое в свою очередь через subSequence() возвращает последовательность символов (CharSequence),  по заданным индексам начала и конца. Или все таки нет, потому что новая память не выделяется под эти операции

2022-12-07 12:46 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    } else if (bMathR().last() == '0' && simEqual(bMathR()[bMathR().length - 2])) {
Первое условие:
if (bMathR().equals("0") || bMathR().last() == '=') {
        bMathW(str)
+
 часть второго условия (bMathR().last() == '0'
исключает возможность прийти строке менее 2 элементов.

2022-12-07 13:07 UTC, merged

2022-12-11 09:52 UTC, fantasianna reviewed
все хорошо! едем дальше!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +        binding.resultBtn.setOnClickListener { btnResult() }
да, отлично вынес все в методы!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            setMathText("0")
для единообразия лучше вообще все внутренности каждого setOnClickListener тут вынести в отдельные методы, но в данном случае всего 2 строчки, не крит

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
>          binding.btn8.setOnClickListener { addNum("8") }
в идеале все биндинги тоже можно вынести в отдельный метод bindViews()

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +private fun buttonPoint() {
с названиями методов еще стоит поработать, они всегда должны начинаться с глагола, это своеобразный код стандарт

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +private fun isDivisionZero(str: String): Boolean {
тут отлично

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    return when {
от when душа радуется! :сердечко:

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    var text = delLastZeros(getMathText())
delLastZeros(getMathText()) - прекрасно! это уже выглядит как самодокументирующийся код!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            if (isSignEqual(text.last())) {
тут много кода внутри ветки else, в таких случаях лучше разбивать на несколько методов, так будет читаеемее

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +                text = text.dropLast(1)
кроме того вот эта последовательность:
text = text.dropLast(1)
                btnDel()
                addStr("=")

повторяется два раза в двух ветках, вот такое точно нужно выносить в отдельный метод и переиспользовать. И еще не понятно зачем две разные ветки ифа, если внутри одно и то же делается? Кажется эти два условия можно было объединить

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            Log.d("Ошибка Result", "В разделе кнопки =, произошла ошибка: ${e.message} ")
за логи - респект!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +private fun getMathText(): String = binding.mathOperation.text.toString()
все эти геттеры и сеттеры тоже прекрасны!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +private fun addNum(str: String) {
метод сложный но читается нормально! Отличная работа!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +            when {
таких вложенных конструкций тоже лучше избегать, они сложно читаются и выносить внутренюю логику в отдельный метод. Больше методов богу методов!!!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +val signMap = setOf('/', '*', '-', '+')
сет!!! ван лав! прекрасно!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +private fun isSignEqual(sign: Char): Boolean = sign in signMap
великолепно!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    str.split(signOne, signTwo).filter { it.isNotEmpty() }.toTypedArray()
стильно! модно! молодежно!

2022-12-11 09:52 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
> +    val arrSimvol = getSign(str, signOne, signTwo)
следи чтобы не проскакивали русские слова в транслитерации

2022-12-13 12:42 UTC, simt11 commented on app/src/main/java/com/example/calculator/MainActivity.kt
>          binding.btn8.setOnClickListener { addNum("8") }
А внутри будут все эти bindingi или как? или они как то будут обьеденены???

2022-12-14 05:23 UTC, fantasianna commented on app/src/main/java/com/example/calculator/MainActivity.kt
>          binding.btn8.setOnClickListener { addNum("8") }
я имею ввиду метод типа:
private fun bindViews() {
        ....
        binding.multBtn.setOnClickListener { createSign("*") }
        binding.plusBtn.setOnClickListener { createSign("+") }
        binding.minusBtn.setOnClickListener { createSign("-") }
        binding.resultBtn.setOnClickListener { btnResult() }
        ......
}
чтобы все клик листнеры в отдельном методе проставлялись, а этот метод bindViews вызывался бы внутри onCreate()